### ISSUE TITLE
CCH-01: Fetch the dishes/food from the API and display them under the correct categories under the page.

### ISSUE THREAD

**Issue by Artyssee** [Artyssee/cantine-choupi#10]
## Tasks

- [ ] Create tests for the fetch wit JEST
- [ ] Fetch the dishes/food on the page with a GET request and place them under the right categories.
- [ ] Document the fetch with JSDoc since the data comes from an external source.

## Testing steps

How to test:

1. Go to the landing page of the site.
2. Check if the dishes/food are loading correctly under the right category
3. Check there are no errors 

## Tested on

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
