### ISSUE TITLE
CCH-01: Fetch the categories from the cantine choupi API and display them on the page

### ISSUE THREAD

**Issue by Artyssee** [Artyssee/cantine-choupi#9]
## Tasks

- [ ] Create tests for the fetch wit JEST
- [ ] Fetch the dishes/food on the page with a GET request.
- [ ] Document the fetch request with JSDoc since the data comes from an external source.

## Testing steps

How to test:

1. Go to the landing page of the site.
2. Check if the dishes/food are loading correctly
3. Check there are no errors 

## Tested on

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
